config/routes.rb
Rails.application.routes.draw do
  get 'sessions/new'
  resources :recommendations 
  get 'users/new'
  root 'static_pages#home'
  get '/help', to: 'static_pages#help'
  get '/about', to: 'static_pages#about'
  get '/contact', to: 'static_pages#contact'
  get '/signup', to: 'users#new'
  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/recommendation.rb
class Recommendation < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
  before_save { self.email = email.downcase }
  validates :name, presence: true, length: { maximum: 50 }
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email, presence: true, length: { maximum: 255 },
                    format: { with: VALID_EMAIL_REGEX },
                    uniqueness: { case_sensitive: false }
  has_secure_password
  validates :password, presence: true, length: { minimum: 6 }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  
  def hello
    render html: "hello world"
  end

end

app/controllers/recommendations_controller.rb
class RecommendationsController < ApplicationController
  before_action :set_recommendation, only: %i[ show edit update destroy ]
  before_action :authenticate

  def authenticate
    if not session[:user_id]
      redirect_to '/'
    end
  end

  # GET /reccomendations or /reccomendations.json
  def index
    @recommendations = Recommendation.all
  end

  # GET /reccomendations/1 or /reccomendations/1.json
  def show
  end

  # GET /reccomendations/new
  def new
    @recommendation = Recommendation.new
  end

  # GET /reccomendations/1/edit
  def edit
  end

  # POST /reccomendations or /reccomendations.json
  def create
    @recommendation = Recommendation.new(recommendation_params)

    respond_to do |format|
      if @recommendation.save
        format.html { redirect_to @recommendation, notice: "Recommendation was successfully created." }
        format.json { render :show, status: :created, location: @recommendation }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @recommendation.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /reccomendations/1 or /reccomendations/1.json
  def update
    respond_to do |format|
      if @recommendation.update(recommendation_params)
        format.html { redirect_to @recommendation, notice: "Recommendation was successfully updated." }
        format.json { render :show, status: :ok, location: @recommendation }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @recommendation.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /reccomendations/1 or /reccomendations/1.json
  def destroy
    @recommendation.destroy
    respond_to do |format|
      format.html { redirect_to recommendations_url, notice: "Recommendation was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_recommendation
      @recommendation = Recommendation.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def recommendation_params
      params.require(:recommendation).permit(:title, :creator, :media, :description)
    end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    user = User.find_by(email: params[:session][:email].downcase)
    if user && user.authenticate(params[:session][:password])
      session[:user_id] = user.id
      redirect_to '/' 
    else 
      flash.now[:danger] = 'Invalid username/password combination'
      render 'new'
    end
  end

  def destroy
  end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
  end

  def help
  end
  
  def about
  end
  
  def contact
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def full_title(page_title = '')
    base_title = 'Ruby on Rails Tutorial Sample App'
    if page_title.empty?
      base_title
    else
      page_title + ' | ' + base_title
    end
  end
end

app/helpers/recommendations_helper.rb
module RecommendationsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/_footer.html.erb
<footer class="footer">
  <div>
    <small>
      Sam's Personal Web Page
    </small>
    <nav>
      <ul>
        <li><%= link_to "Home", root_path %></li>
        <li><%= link_to "Contact", contact_path %></li>
        <li><%= link_to "Recommendations", help_path %></li>
      </ul>
    </nav>
  </div>
</footer>

app/views/layouts/_reccomendation.html.erb
<div class="col-lg-3">
  <div class="recommendation card">
    <div class="card-header">
      <h3><%= @recommendation.title %></h1>
      <h5>By: <span><%= @recommendation.creator %></span></h4>
      <h5>Medium: <span><%= @recommendation.media %></span></h4>
    </div>
    <div class="card-body">
      <p><%= @recommendation.description %></p>
    </div>
  </div>
</div>

    

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= full_title(yield(:title)) %></title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <header class="navbar navbar-inverse">
      <div>
        <%= link_to "Contact", contact_path, id: "logo", class:"navbar-brand" %>
        <nav>
          <ul class="nav navbar-nav navbar-right">
            <li><%= link_to "Home", root_path %></li>
            <li><%= link_to "Recommendations", help_path %></li>
            <li><%= link_to "Log In", login_path %></li>
          </ul>
        </nav>
      </div>
    </header>
    <%= yield %>
    <%= render 'layouts/footer' %>
  </body>
</html>

app/views/recommendations/_form.html.erb
<%= form_with(model: recommendation, local: true) do |form| %>
  <% if recommendation.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(recommendation.errors.count, "error") %> prohibited this reccomendation from being saved:</h2>

      <ul>
        <% recommendation.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title %>
  </div>

  <div class="field">
    <%= form.label :creator %>
    <%= form.text_field :creator %>
  </div>

  <div class="field">
    <%= form.label :media %>
    <%= form.text_field :media %>
  </div>

  <div class="field">
    <%= form.label :description %>
    <%= form.text_field :description %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/recommendations/edit.html.erb
<h1>Editing Reccomendation</h1>

<%= render 'form', recommendation: @recommendation %>

<%= link_to 'Show', @recommendation %> |
<%= link_to 'Back', recommendations_path %>

app/views/recommendations/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Recommendations</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Creator</th>
      <th>Media</th>
      <th>Description</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @recommendations.each do |recommendation| %>
      <tr>
        <td><%= recommendation.title %></td>
        <td><%= recommendation.creator %></td>
        <td><%= recommendation.media %></td>
        <td><%= recommendation.description %></td>
        <td><%= link_to 'Show', recommendation %></td>
        <td><%= link_to 'Edit', edit_recommendation_path(recommendation) %></td>
        <td><%= link_to 'Destroy', recommendation, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Recommendation', new_recommendation_path %>

app/views/recommendations/new.html.erb
<h1>New Recommendation</h1>

<%= render 'form', recommendation: @recommendation %>

<%= link_to 'Back', recommendations_path %>

app/views/recommendations/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @recommendation.title %>
</p>

<p>
  <strong>Creator:</strong>
  <%= @recommendation.creator %>
</p>

<p>
  <strong>Media:</strong>
  <%= @recommendation.media %>
</p>

<p>
  <strong>Description:</strong>
  <%= @recommendation.description %>
</p>

<%= link_to 'Edit', edit_recommendation_path(@recommendation) %> |
<%= link_to 'Back', recommendations_path %>

app/views/static_pages/about.html.erb
<% provide(:title, "About") %>
<h1>About</h1>
<p>This is the about page for the<ahref="https://www.railstutorial.org/">Ruby on Rails Tutorial</a>sample application.</p>
  

app/views/static_pages/contact.html.erb
<% provide(:title, "Contact") %>
<div id="contactsection">
  <div class="contact row" id="contactrow">
    <div class="col-lg-6" id="headcol">
      <h1 class="contact">Contact</h1>
      <h3 class="text-muted" style="margin-left: 7%">Feel free to get in touch!</h3>
    </div>
    <div class="col-lg-6 cream">
      <ul class="contact">
        <li>Email: eagensam@grinnell.edu</li>
        <li>Phone: Currently Unavailable</li>
        <li>Github: <a href="https://github.com/sve009">https://github.com/sve009</a></li>
      </ul>
    </div>
  </div>
</div>

app/views/static_pages/help.html.erb
<% provide(:title, "Recommendations") %>
<div class="center container">
  <h1 id=reccos>Recommendations</h1>
  <h4 class="text-muted" id="subheader">I do things sometimes, here are some things I've enjoyed</h4>
  <div class="row">
    <% @recommendations = Recommendation.all %>
    <% @recommendations.each() do |recommendation| %>
      <% @recommendation = recommendation %>
      <%= render 'layouts/reccomendation' %>
    <% end %>
  </div>
</div>
  

app/views/static_pages/home.html.erb
<div class="center title jumbotron jumbotron-fluid">
  <div class="container">
    <h1 id="heading">Sam Eagen</h1>
    <p>A website that probably no one will ever see.</p>
    <%= link_to "Check Me Out", "https://github.com/sve009", class: "btn btn-lg btn-primary" %>
  </div>
</div> 

<div class="container">
  <h1 id="projects">Projects:</h1>
  <div class="row">
    <div class="col-lg-3">
      <div class="center card">
        <div class="card-header">
          <h5>MICA Food Pantry</h5>
        </div>
        <div class="card-body">
          An app designed to keep track of which items
          the food pantry is currently in the most need of.
          This allows provides consumers with information about
          what donations are currently the most helpful.
        </div>
        <div class="card-footer">
          <a href="https://github.com/sve009/MICA_foodpantry" class="btn btn-lg">Check it out</a>
        </div>
      </div>
    </div>
    <div class="col-lg-3">
      <div class="center card">
        <div class="card-header">
          <h5>Secondary Extinction Simulation</h5>
        </div>
        <div class="card-body">
            Uses networks to model food chain collapse,
            allowing for the the robustness of ecosystem
            structures to be tested against variables such
            as diversity.
        </div>
        <div class="card-footer">
          <a  href="https://github.com/sve009/SecondaryExtinctionProject" class="btn btn-lg">Check it out</a>
        </div>
      </div>
    </div>
    <div class="col-lg-3">
      <div class="center card">
        <div class="card-header">
          <h5>Pong AI</h5>
        </div>
        <div class="card-body">
          <p>
            A reinforcement learning project that uses reinforcement
            learning to train a neural network to give the desired
            action for a player every tick based on the ball position
            and velocity.
          </p>
        </div>
        <div class="card-footer">
          <a class="btn btn-lg" href="https://github.com/sve009/PongRL">Check it out</a>
        </div>
      </div>
    </div>
    <div class="col-lg-3">
      <div class="center card">
        <div class="card-header">
          <h5>Polynomial CAS</h5>
        </div>
        <div class="card-body">
          <p>
            A binary and library for working with multivariate polynomials.
            Additionally, has more advanced functionalities
            such as providing the user choices of monomial orderings, and can even
            solve Groebner bases of ideals. All implemented in Rust.
          </p>
        </div>
        <div class="card-footer d-flex align-items-end">
          <a class="btn btn-lg" href="https://github.com/sve009/RustPolynomialOperations">Check it out</a>
        </div>
      </div>
    </div>
  </div>
</div>

<div class="jumbotron jumbotron-fluid inverse">
  <div class="container">
    <div class="row">
      <div class="col-lg-5">
        <h1>About Me:</h1>
        <div id="harry">
          <%= image_tag "harry.jpg" %>
          <p>My cat, Harry, having a flower snack</p>
        </div>
      </div>
      <div class="col-lg-7">
        <div class="row">
          <div class="col-lg-4">
            <h3>Background</h3>
            <p>
              I'm from Versailles KY, and am a computer science and math major
              at Grinnell college. I am male identifying, and I love problem-solving and collaboration.
              In my freetime I often enjoy doing personal projects to develop new skills. 
            </p>
          </div>
          <div class="col-lg-4">
            <h3>Hobbies</h3>
            <p>
              I love board games, video games, and reading novels. Currently,
              I'm racking up hours playing Monster Hunter Rise and finishing
              up schoolwork. 
            </p>
          </div>
          <div class="col-lg-4">
            <h3>Skills</h3>
            <p>
              I've been lucky enough to have the opportunity to work on projects in many
              languages, including python, java, javascript, rust, haskell, ruby, and
              julia. I've also gotten to work on many different types of project, from
              more typical web-apps to polymorphic type-driven program synthesis engines.
            </p>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/users/new.html.erb
<% provide(:title, "Sign Up") %>
<h1>Sign Up</h1>
<p>This will be the signup page.</p>